<?php

declare(strict_types=1);

/**
 * @file
 * Provides a product prices entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function product_prices_theme(): array {
  return [
    'product_price' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for product prices templates.
 *
 * Default template: product-price.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the product prices information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_product_price(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
