name: 'Products'
type: module
description: 'Provides the Product entity'
package: Custom
core_version_requirement: ^11.2
dependencies:
  - drupal:text
  - drupal:user
  - published_access:published_access
