name: 'Product Prices'
type: module
description: 'Provides the pricing structure for Products'
package: Custom
core_version_requirement: ^10 || ^11
dependencies:
  - customers:customers
  - products:products
  - util:money_field
