<?php

declare(strict_types=1);

/**
 * @file
 * Provides a customer entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function customers_theme(): array {
  return [
    'customer' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for customer templates.
 *
 * Default template: customer.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the customer information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_customer(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function customers_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish customers.
      $storage = \Drupal::entityTypeManager()->getStorage('customer');
      $customer_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($customer_ids) as $customer) {
        $customer->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize customers.
      $storage = \Drupal::entityTypeManager()->getStorage('customer');
      $customer_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($customer_ids) as $customer) {
        $customer->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function customers_user_predelete(UserInterface $account): void {
  // Delete customers that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('customer');
  $customer_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($customer_ids)
  );
}
